### PR TITLE
Explicitly set placeholder name while creating FxGraph node

### PR DESCRIPTION
**Pull request by anijain2305**
Fixes https://github.com/pytorch/torchdynamo/issues/762

@ezyang

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Comment by ezyang** [comment]
I'd love to know why this works. Is it because we were putting illegal characters in the name before?

**Comment by voznesenskym** [comment]
> I'd love to know why this works. Is it because we were putting illegal characters in the name before?

I think its cause of the line(s) below:

```
 used_names = {n.name for n in placeholders}
        if name in used_names:
            for i in itertools.count():
                if f"{name}_{i}" not in used_names:
                    name = f"{name}_{i}"
                    break
```

**Comment by anijain2305** [comment]
Yes, @voznesenskym has it right. Basically, the name that we send to Fx `create_node` API is different from the name that's actually assigned to the placeholder node. So, our unique name generation logic is not able to handle this difference.

**Comment by ezyang** [comment]
Tracer.create_proxy calls create_node calls Graph.create_node, which says

```
            name (Optional[str]): an optional string name for the ``Node``.
                This will influence the name of the value assigned to in the
                Python generated code.
```

in other words, `create_node` is supposed to guarantee that the generated name is unique. If this is not working, there is some deeper problem with FX itself or our use of the API.

**Comment by anijain2305** [comment]
> Tracer.create_proxy calls create_node calls Graph.create_node, which says
> 
> ```
>             name (Optional[str]): an optional string name for the ``Node``.
>                 This will influence the name of the value assigned to in the
>                 Python generated code.
> ```
> 
> in other words, `create_node` is supposed to guarantee that the generated name is unique. If this is not working, there is some deeper problem with FX itself or our use of the API.

Thanks for encouraging me to look into this. We were not passing name to `create_node`. Instead, it was relying on `target` to come up with a candidate  here - https://github.com/pytorch/pytorch/blob/master/torch/fx/graph.py#L728

After you suggestion, I explicitly setup `name` arg. I checked the new fix on VDD as well, and its passing.

**Review by ezyang — APPROVED** [review]

**Pull request merged**
