### PR TITLE
Delete offline autotuner

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #1053
* #1052
* #1051
* #1049
* __->__ #1047
* #1042

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by jansel** [comment]
I think we can also remove this entire file: https://github.com/pytorch/torchdynamo/blob/main/benchmarks/autotune.py

**Comment by ezyang** [comment]
did it in another pr in the stack

**Comment by zzpmiracle** [comment]
Sorry, @ezyang @jansel why do we delete the autotuner? I think it a nice work in torchdynamo to capare backends for each subgraph. Does it not work or have some side-effects?

**Comment by ezyang** [comment]
The offline autotuner is not good for general use, as it requires a lot of work on the users part; you'd rather just have one backend that works well for everything. Additionally we were not maintaining this code. You are welcome to run your own autotuning experiments if you like!

**Pull request merged**
