### PR TITLE
Fix type conversion issues for logical ops

### PR DESCRIPTION
**Pull request by desertfire**
Summary: https://github.com/pytorch/torchdynamo/issues/1359

Test Plan:
PYTORCH_ALL_SAMPLES=1 pytest test/test_torchinductor_opinfo.py -k test_comprehensive_logical

### CODE REVIEW

**Comment by desertfire** [comment]
I also renamed some flags in `lowering.py` to make them more meaningful.

**Comment by desertfire** [comment]
> Looks good, if CI agrees.

Hmm, somehow CI gives a different result on fft.ifft and fft.ihfft. Reverting anyway.

**Review by eellison — COMMENTED** [review]
any thought of using prims here ? that's their intended purpose right

**Review by jansel — APPROVED** [review]

**Comment by ngimel** [comment]
It is, but prims bundle explicit broadcasting and type promotion and we need only the latter.

**Pull request merged**
