### PR TITLE
Delete python key mode

### PR DESCRIPTION
**Pull request by ezyang**
AOTAutograd subsumes this mode (in particular, if AOTAutograd
gets a graph with no requires grad, or with no_grad on, it should not bother to
wrap the function in a custom autograd.Function); so if you have feature
requests for this, send them to AOTAutograd.  If you need a cheap and
cheerful lowering, you can use make_fx().

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by Chillee** [comment]
There are some ... lingering issues, mainly related to in-place ops I believe.

**Comment by ezyang** [comment]
yes well we should fix them...

**Comment by Chillee** [comment]
I think this should fix them: https://github.com/pytorch/pytorch/pull/82520

But I know @voznesenskym is also using this file somehow?

**Review by jansel — APPROVED** [review]

**Comment by voznesenskym** [comment]
> I think this should fix them: https://github.com/pytorch/pytorch/pull/82520
> 
> 
> 
> But I know @voznesenskym is also using this file somehow?

I was, but I worked around it.

**Review by anijain2305 — APPROVED** [review]

**Review by voznesenskym — APPROVED** [review]

**Comment by ezyang** [comment]
This is blocked on https://github.com/pytorch/pytorch/pull/82520

**Comment by ezyang** [comment]
This PR identifies some known soundness issues with AOTAutograd and mutation.

**Comment by Chillee** [comment]
I've verified that this PR + https://github.com/pytorch/pytorch/pull/83361 pass torchinductor tests.

side note: One of my recent PRs (https://github.com/pytorch/pytorch/pull/83248) is causing failures due to moving compilation out of autograd.Function and into a context that potentially has grad set.

https://github.com/pytorch/pytorch/pull/83361 fixes it, but you can also fix it by patching in the changes in `aot_autograd.py` in the above PR (https://github.com/pytorch/pytorch/pull/83361/files#diff-49334b500179bfa6b103db889c6bb8fe6984f6baa5fe73cef6b8ea59bbc0775bR265).

cc: @jansel

**Comment by voznesenskym** [comment]
Not having this committed puts our fbcode integration in a bad state. I can resolve it manually, but we should get this in.

This class is the last place where we import PythonTensor. Not noticed in dynamo, but fbcode evaluates imports differently and hits this assertion.

@ezyang if you dont have time, I can take over getting through the merge conflicts and getting it in.

**Comment by Chillee** [comment]
@voznesenskym I was actually looking at this, but unfortunately, even after my landed PRs, it doesn't fix all tests (due to tracing in-place modifying inputs). I can take another look at landing it.

**Comment by voznesenskym** [comment]
> @voznesenskym I was actually looking at this, but unfortunately, even after my landed PRs, it doesn't fix all tests (due to tracing in-place modifying inputs). I can take another look at landing it.

Ah rats - alright, no problem. LMK how I can help here. This is probably higher than the broadcast / tl.where bugs I am looking at cause its making internal integration a bit of a pain...

**Comment by Chillee** [comment]
Gonna close this one in favor of a new one, as quite a bit has changed.

**Comment by Chillee** [comment]
In favor of https://github.com/pytorch/torchdynamo/pull/939

**Pull request closed without merging**
