### PR TITLE
Copy meta when swapping nodes

### PR DESCRIPTION
**Pull request by SherlockNoMad**

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by voznesenskym** [comment]
We had this PR before, and it failed some benchmarks w/ errors - can you run the same benchmarks it failed with last time? https://github.com/pytorch/torchdynamo/issues/929 (Run command is in there)

**Comment by SherlockNoMad** [comment]
> We had this PR before, and it failed some benchmarks w/ errors - can you run the same benchmarks it failed with last time? #929 (Run command is in there)

Previous failure is coming from this line 
```
assert not new_node.meta, "New node must not have meta populated"
```

**Comment by voznesenskym** [comment]
> > We had this PR before, and it failed some benchmarks w/ errors - can you run the same benchmarks it failed with last time? #929 (Run command is in there)
> 
> Previous failure is coming from this line
> 
> ```
> assert not new_node.meta, "New node must not have meta populated"
> ```

I know, but it wouldn't hurt to test. This is a very critical codepath and we should be careful.

**Review by voznesenskym — APPROVED** [review]

**Comment by ezyang** [comment]
we should be running a quick benchmark suite run in ci...

**Comment by SherlockNoMad** [comment]
> > > We had this PR before, and it failed some benchmarks w/ errors - can you run the same benchmarks it failed with last time? #929 (Run command is in there)
> > 
> > 
> > Previous failure is coming from this line
> > ```
> > assert not new_node.meta, "New node must not have meta populated"
> > ```
> 
> I know, but it wouldn't hurt to test. This is a very critical codepath and we should be careful.

Tried on timm_efficientnet, timm_nfnet, timm_regnet, timm_resnest, timm_vision_transformer, timm_vovnet, and passing without problem.

**Pull request merged**
