### PR TITLE
[inductor] reshape ranges only when used

### PR DESCRIPTION
**Pull request by pyjhzwh**
SHOULD NOT MERGE NOW because of triton bug "map::at error"
- generate 1-dim ranges without reshape
- reshape ranges only when used in load/store/reduction
- reshape data to multi-dim after loaded if needed

Previously
```
xoffset = tl.program_id(0) * XBLOCK
xindex = xoffset + tl.arange(0, XBLOCK)[:, None] # reshape index here
xmask = xindex < xnumel
tmp0 = tl.load(in_ptr0 + ks0*(x0)), xmask)
```

Now
```
xoffset = tl.program_id(0) * XBLOCK
xindex = xoffset + tl.arange(0, XBLOCK) # do not reshape index here, reshape it when used
xmask = xindex < xnumel
tmp0 = tl.load(in_ptr0 + ks0*(x0[:, None])), xmask[:, None])
```

### CODE REVIEW

**Comment by pyjhzwh** [comment]
`make test` will failed because of triton issue: https://github.com/openai/triton/issues/576
```
FAILED tests/test_torchinductor.py::GpuTests::test_log_softmax_cuda - IndexError: map::at
FAILED tests/test_torchinductor.py::GpuTests::test_logsumexp_cuda - IndexError: map::at
FAILED tests/test_torchinductor.py::GpuTests::test_softmax_cuda - IndexError: map::at
FAILED tests/test_torchinductor.py::GpuTests::test_std_cuda - IndexError: map::at
FAILED tests/test_torchinductor.py::GpuTests::test_var_mean_cuda - IndexError: map::at
```

**Comment by jansel** [comment]
For the mat:at errors, does changing:
```
tmp0 = tl.load(in_ptr0 + ks0*(x0[:, None])), xmask)
```
to
```
tmp0 = tl.load(in_ptr0 + ks0*(x0[:, None])), xmask[:, None])
```
fix it?

I think the masks need to be broadcast too.

**Comment by pyjhzwh** [comment]
> For the map::at errors, does changing:
> 
> ```
> tmp0 = tl.load(in_ptr0 + ks0*(x0[:, None])), xmask)
> ```
> 
> to
> 
> ```
> tmp0 = tl.load(in_ptr0 + ks0*(x0[:, None])), xmask[:, None])
> ```
> 
> fix it?
> 
> I think the masks need to be broadcast too.

My bad. I missed xmask[:, None] when copy/paste the example code. The codegen would reshape both index and mask.

**Comment by jansel** [comment]
We have migrated `torchdynamo` to `torch._dynamo` and will use the `pytorch/pytorch` repo for future development.  Please resubmit this PR to https://github.com/pytorch/pytorch/

More details and instructions to port this PR over can be found in https://github.com/pytorch/torchdynamo/issues/1588

**Pull request closed without merging**
