### PR TITLE
Revert "Enable guard_nn_modules - Observe module changes to drive inv…

### PR DESCRIPTION
**Pull request by jansel**
…alidation instead of id_match + training guards (#326)"

This reverts commit c74758022b438e3e9bd31c8b0775d47b022fef4b.

This PR is causing infinite loops in inductor training. To repro checkout the repro326 branch https://github.com/pytorch/torchdynamo/tree/repro326 and run:
```
./benchmarks/torchbench.py -dcuda --inductor --training --float16 -k attention_is_all_you_need_pytorch
```
(This should also repro on main once all my pending PRs are merged)

Output:
```
Traceback (most recent call last):
  File "./benchmarks/torchbench.py", line 340, in <module>
    main(TorchBenchmarkRunner(), original_dir)
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 1169, in main
    runner.run_one_model(
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 649, in run_one_model
    model_iter_fn(model, example_inputs)
  File "./benchmarks/torchbench.py", line 328, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/torchbenchmark/torchbenchmark/models/attention_is_all_you_need_pytorch/transformer/Models.py", line 172, in forward
    dec_output, *_ = self.decoder(trg_seq, trg_mask, enc_output, src_mask)
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/torchbenchmark/torchbenchmark/models/attention_is_all_you_need_pytorch/transformer/Models.py", line 101, in forward
    def forward(self, trg_seq, trg_mask, enc_output, src_mask, return_attns=False):
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 97, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 642, in forward
    return compiled_f(
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 97, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 187, in forward
    fx_g = make_fx(joint_forward_backward, aot_decompositions)(
  File "/home/jansel/pytorch/torch/fx/experimental/proxy_tensor.py", line 281, in wrapped
    t = dispatch_trace(wrap_key(f, args), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 97, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/pytorch/torch/fx/experimental/proxy_tensor.py", line 179, in dispatch_trace
    return GraphModule(tracer.root, graph, name)
  File "/home/jansel/pytorch/torch/fx/graph_module.py", line 366, in __init__
    self.graph = graph
  File "/home/jansel/torchdynamo/torchdynamo/guards.py", line 111, in custom_setattr
    return original_setattr(self, key, value)
  File "/home/jansel/torchdynamo/torchdynamo/guards.py", line 111, in custom_setattr
    return original_setattr(self, key, value)
  File "/home/jansel/torchdynamo/torchdynamo/guards.py", line 111, in custom_setattr
    return original_setattr(self, key, value)
  [Previous line repeated 490 more times]
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1309, in __setattr__
    super().__setattr__(name, value)
  File "/home/jansel/pytorch/torch/fx/graph_module.py", line 402, in graph
    self._graph = g
  File "/home/jansel/torchdynamo/torchdynamo/guards.py", line 111, in custom_setattr
    return original_setattr(self, key, value)
  File "/home/jansel/torchdynamo/torchdynamo/guards.py", line 111, in custom_setattr
    return original_setattr(self, key, value)
  File "/home/jansel/torchdynamo/torchdynamo/guards.py", line 111, in custom_setattr
    return original_setattr(self, key, value)
  [Previous line repeated 476 more times]
  File "/home/jansel/torchdynamo/torchdynamo/guards.py", line 110, in custom_setattr
    NNModuleChangeTrackerUtil.invalidate_module(self)
  File "/home/jansel/torchdynamo/torchdynamo/guards.py", line 135, in invalidate_module
    if module not in module_code_map:
  File "/home/jansel/torchdynamo/torchdynamo/utils.py", line 103, in __contains__
    return id(key) in self.values
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]
My saddest stamp

**Comment by voznesenskym** [comment]
@jansel I am getting:

```
Traceback (most recent call last):
  File "./benchmarks/torchbench.py", line 340, in <module>
    main(TorchBenchmarkRunner(), original_dir)
  File "/scratch/voz/work/torchdynamo/benchmarks/common.py", line 1156, in main
    device, name, model, example_inputs = runner.load_model(
  File "./benchmarks/torchbench.py", line 250, in load_model
    benchmark = benchmark_cls(
  File "/scratch/voz/work/benchmark/repr/util/model.py", line 14, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/scratch/voz/work/benchmark/repr/models/attention_is_all_you_need_pytorch/__init__.py", line 95, in __init__
    train_data, test_data = prepare_dataloaders(self.opt, self.device)
  File "/scratch/voz/work/benchmark/repr/models/attention_is_all_you_need_pytorch/train.py", line 333, in prepare_dataloaders
    data = pickle.load(open(opt.data_pkl, 'rb'))
  File "/data/home/voz/miniconda/envs/repr/lib/python3.8/site-packages/dill/_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/data/home/voz/miniconda/envs/repr/lib/python3.8/site-packages/dill/_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "tokenizer.pyx", line 67, in spacy.tokenizer.Tokenizer.__init__
  File "tokenizer.pyx", line 424, in spacy.tokenizer.Tokenizer._load_special_tokenization
  File "tokenizer.pyx", line 440, in spacy.tokenizer.Tokenizer.add_special_case
  File "vocab.pyx", line 262, in spacy.vocab.Vocab.make_fused_token
  File "morphology.pyx", line 287, in spacy.morphology.Morphology.assign_tag
  File "morphology.pyx", line 311, in spacy.morphology.Morphology.assign_tag_id
  File "morphology.pyx", line 245, in spacy.morphology.Morphology.lemmatize
  File "/data/home/voz/miniconda/envs/repr/lib/python3.8/site-packages/spacy/lemmatizer.py", line 55, in __call__
    if callable(self.is_base_form) and self.is_base_form(univ_pos, morphology):
  File "/data/home/voz/miniconda/lib/python3.9/site-packages/spacy/lang/en/__init__.py", line 49, in is_base_form
    if morphology is None:
SystemError: unknown opcode
```

When I run - can you tell me your python version?

**Comment by jansel** [comment]
> My saddest stamp

Yeah, disappointing... hopefully an easy fix!

**Comment by jansel** [comment]
I am using python 3.8, and building the latest version of pytorch/functorch/triton from source.

**Pull request merged**
