### PR TITLE
[WIP] Let Dynamo step through DistributedDataParallel forward

### PR DESCRIPTION
**Pull request by anijain2305**
cc @wconstab @davidberard98

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Review by davidberard98 — APPROVED** [review]
This fixes our resnet50 issue.

**Comment by anijain2305** [comment]
@davidberard98 I am hesitating to merge this because I think we can add a category of ops for which we want Dynamo to let in. This could be FSDP very soon.

Do you want to take a stab at this? Basically add a category in allowed_functions.py and if nn_module falls in that category, we let Dynamo step in. Let me know if thats ok.

**Comment by wconstab** [comment]
> I am hesitating to merge this because I think we can add a category of ops for which we want Dynamo to let in. This could be FSDP very soon.

**Comment by anijain2305** [comment]
Ok, we can do a refactor later. We can land this for now.

I don;t expect this to be many modules, but I do expect a few related to distributed, like FSDP and DDP, maybe the param_flat thing that you are seeing as well.

**Pull request merged**
