### PR TITLE
Move Functorch Config Change

### PR DESCRIPTION
**Pull request by eellison**
Following https://github.com/pytorch/torchdynamo/pull/1096 - according to @anijain2305 previous import may caused circular import

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Review by anijain2305 — DISMISSED** [review]
Wait this might only enable it for Aot Autograd. We need it for inductor as well

https://github.com/pytorch/torchdynamo/blob/main/torchinductor/compile_fx.py#L234

**Review by desertfire — APPROVED** [review]
LGTM

**Review by Chillee — COMMENTED** [review]
Since fake tensor/functionalize are enabled in core, can we just delete these from here lol.

**Comment by eellison** [comment]
> Since fake tensor/functionalize are enabled in core, can we just delete these from here lol. 
I still need to land that haha

**Pull request merged**
