### PR TITLE
Add version comments to minifier for easier to reproduce repros

### PR DESCRIPTION
**Pull request by voznesenskym**
Sample of what the top of the Repro file looks like now:

```
import torch
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torchinductor.compile_fx import compile_fx_inner
from torch.fx.experimental.proxy_tensor import make_fx

# torch version: 1.13.0.dev20220807+cu116
# torch cuda version: 11.6
# torch git version: c50657628024720a25aa07ba3d2db1e6a8ba021b


# nvcc: NVIDIA (R) Cuda compiler driver 
# Copyright (c) 2005-2022 NVIDIA Corporation 
# Built on Thu_Feb_10_18:23:41_PST_2022 
# Cuda compilation tools, release 11.6, V11.6.112 
# Build cuda_11.6.r11.6/compiler.30978841_0 


class Repro(torch.nn.Module):
```

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by soumith** [comment]
you would also want to report the GPU model.

**Comment by voznesenskym** [comment]
> you would also want to report the GPU model.

I am not opposed. I was considering doing this via `nvidia-smi` but that felt spammy. Let me see if I can find a way to make a nice small report of that.

**Review by Chillee — APPROVED** [review]
Looks awesome!

**Comment by voznesenskym** [comment]
Updated to:

```
# torch version: 1.13.0a0+git1e98c87
# torch cuda version: 11.6
# torch git version: 1e98c87d38384cf8de79d0365c4feb9a9befd2b5


# CUDA Info: 
# nvcc: NVIDIA (R) Cuda compiler driver 
# Copyright (c) 2005-2022 NVIDIA Corporation 
# Built on Thu_Feb_10_18:23:41_PST_2022 
# Cuda compilation tools, release 11.6, V11.6.112 
# Build cuda_11.6.r11.6/compiler.30978841_0 

# GPU Hardware Info: 
# NVIDIA A100-SXM4-40GB : 8 
```

**Pull request merged**
