### PR TITLE
Disabling TorchDynamo inside torch.jit and torch.onnx compiler

### PR DESCRIPTION
**Pull request by anijain2305**
* Helps with many PyTorch JIT tests.  Only 7 test/jit/* failures now. 
* All 136 failures with test/onnx/* are resolved.

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Can we do this without monkey patching?  Perhaps something similar to skipfiles?  Skipfunctions?

**Comment by anijain2305** [comment]
Its not just the frame of `torch.jit.trace`, instead it's the inner frames in the execution of `torch.jit.trace` which causes problems. TorchDynamo changes the bytecode of the inner frames, which changes `torch.jit.trace` result, and causes test failures.

So, I need something like `disable`. IIUC, `skip` just skips one frame, and not the inner frames. What do you think?

**Comment by anijain2305** [comment]
> I see, in that case lets create a file like `torchdynamo/patch_torch.py` to make these easier to find. Let's do the patches on the first call to `torchdynamo.optimize` rather than at import time.
> 
> You could move this one to that file as well:
> 
> https://github.com/pytorch/torchdynamo/blob/85561d0f4f656af71e0f3fa9f56af61466ac8f7c/torchdynamo/allowed_functions.py#L103

Nice! This is cleaner. Let me do that.

**Comment by anijain2305** [comment]
Also, should I put I unpatch it using __enter__ and __exit__ if we are in `torchdynamo.optimize`?

**Comment by jansel** [comment]
No, I'd just patch it once with something like `functools.lru_cache()`

**Review by jansel — APPROVED** [review]

**Pull request merged**
