### PR TITLE
Move the triton pin

### LINKED ISSUE #1564: [inductor] `le` view is different between Inductor and Torch
I am not sure if this is a problem or really a root cause of the problems I am seeing. But, wanted to get other opinions on this.

@ngimel @jansel 

~~~

import torch
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

# torch version: 1.14.0a0+git4bfe2a2
# torch cuda version: 11.6
# torch git version: 4bfe2a24505049fa4fe43d24c2e3a5f5d99d9f00


# CUDA Info:
# nvcc: NVIDIA (R) Cuda compiler driver
# Copyright (c) 2005-2022 NVIDIA Corporation
# Built on Thu_Feb_10_18:23:41_PST_2022
# Cuda compilation tools, release 11.6, V11.6.112
# Build cuda_11.6.r11.6/compiler.30978841_0

# GPU Hardware Info:
# NVIDIA A100-SXM4-40GB : 8


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()



    def forward(self, _to_copy_402):
        le_23 = torch.ops.aten.le.Scalar(_to_copy_402, 0);  _to_copy_402 = None
        return (le_23,)

args = [((2, 192, 17, 17), (55488, 289, 17, 1), torch.float32, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro())(*args)


ref = mod(*args)[0]

from torchinductor.compile_fx import compile_fx_inner
from torchdynamo.debug_utils import same_two_models

compiled = compile_fx_inner(mod, args)
res = compiled(*args)[0]

assert torch.allclose(ref, res)

ref_u8 = ref.view(dtype=torch.uint8)
res_u8 = res.view(dtype=torch.uint8)
assert torch.allclose(ref_u8, res_u8)
~~~

### PR DESCRIPTION
**Pull request by desertfire**
WARNING: you need to upgrade triton after this PR.

Summary: 
* The pinned version has a proper fix for https://github.com/pytorch/torchdynamo/issues/1450
* Also fixes #1564

### CODE REVIEW

**Comment by jansel** [comment]
I think some stuff in the new runtime changed (added some args), so we may need to update things.

**Comment by jansel** [comment]
https://github.com/pytorch/torchdynamo/issues/1577

**Comment by desertfire** [comment]
> I think some stuff in the new runtime changed (added some args), so we may need to update things.

I can take a look if you are not already working on it. 

Another problem here is similar to https://github.com/pytorch/torchdynamo/issues/1580. Since we don't invalidate codecache if triton version changes, we could start to see different behavior for tests locally.

**Comment by jansel** [comment]
https://github.com/openai/triton/issues/760#issuecomment-1273978555

**Comment by Jokeren** [comment]
I see. Since you are calling the `c_wrapper` function directly, passing None to hooks is a valid fix.

**Review by ngimel — APPROVED** [review]

**Pull request merged**
