### PR TITLE
Add col2im decomposition and remove fallback

### PR DESCRIPTION
**Pull request by lezcano**
We should merge this PR after the stack https://github.com/pytorch/pytorch/pull/85541 is merged.

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by desertfire** [comment]
@lezcano , can we rebase and retest this? I am seeing `AttributeError: '_OpNamespace' 'aten' object has no attribute 'col2im_backward'` with the latest pytorch build.

**Comment by lezcano** [comment]
I was waiting for one day, as I could just pin it to the nightly of the 2nd of Oct, and the merge had happened the 3rd of Oct. Now it should hopefully work.

**Comment by lezcano** [comment]
The failures seem real :/

**Comment by lezcano** [comment]
Superseded by https://github.com/pytorch/torchdynamo/pull/1457/ and https://github.com/pytorch/torchdynamo/pull/1453

**Pull request closed without merging**
