### PR TITLE
Run torch inductor test on GPU machine (Part 1) 

### LINKED ISSUE #255: Add GPU testing to CI
Currently we only test the CPU backends.

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Fixes #255 

Next PR will update test-inductor.yml to use GPU pool.

### CODE REVIEW

**Comment by jansel** [comment]
You might need to update this line to install the GPU version of PyTorch:
https://github.com/pytorch/torchdynamo/blob/f21fd574dd7b07e3959103106c88bdfe27ca9e8c/Makefile#L45

**Comment by SherlockNoMad** [comment]
> You might need to update this line to install the GPU version of PyTorch:
> 
> https://github.com/pytorch/torchdynamo/blob/f21fd574dd7b07e3959103106c88bdfe27ca9e8c/Makefile#L45

OK, will add in the next PR. 
Nikita mentioned that I need to land scale-config.yml first.

**Review by jansel — APPROVED** [review]

**Comment by malfet** [comment]
Do you guys want pytorch-bot to be installed for dynamo?

**Comment by SherlockNoMad** [comment]
> Do you guys want pytorch-bot to be installed for dynamo? Edit[installed]: https://hud.pytorch.org/hud/pytorch/torchdynamo/main should populate soon

I don't think pytorchbot is as urgently needed as in the main repo, as the build is pretty fast for torchdynamo CIs.
However, if pytorchbot can work across all torch org repos, I think it will be really cool!

**Pull request merged**
