### PR TITLE
Add warning on using context manager

### PR DESCRIPTION
**Pull request by anijain2305**
@jansel Does this look ok? I want to tell users to avoid using context manager.

### CODE REVIEW

**Comment by jansel** [comment]
Doesn't the decorator call the context manager?  Will this just warn all the time?

**Comment by voznesenskym** [comment]
Can we just be bold and remove it now? This warning into deprecated into deleted flow doesn't hold much water when we are still in a pretty experimental and early stage, IMO. In semver terms, we are not yet 1.0.0 ;)

**Comment by anijain2305** [comment]
> Doesn't the decorator call the context manager? Will this just warn all the time?

Decorator goes through `__call__` function here
https://github.com/pytorch/torchdynamo/blob/9292e4013c17f01c5b371fabcd6d5a2b1d9ba749/torchdynamo/eval_frame.py#L116

I am adding warning in the `__enter__` method which is called only with context manager. CI is failing because export is using context manager which I can quickly fix 
https://github.com/pytorch/torchdynamo/blob/9292e4013c17f01c5b371fabcd6d5a2b1d9ba749/torchdynamo/eval_frame.py#L466-L471

**Comment by anijain2305** [comment]
> Can we just be bold and remove it now? This warning into deprecated into deleted flow doesn't hold much water when we are still in a pretty experimental and early stage, IMO. In semver terms, we are not yet 1.0.0 ;)

I would totally be on board with that. What do you think @jansel ?

**Comment by jansel** [comment]
Perhaps to an fbgs search to check for usage in fbcode first.

**Comment by anijain2305** [comment]
> Perhaps to an fbgs search to check for usage in fbcode first.

Ok, there are 4-5 places which seem like demos. But, I just realized that we Pytorch tests use this anyways. Lets try to get this one in first. And then clean up Pytorch and fb-internals and come back and remove the warning.

**Review by jansel — APPROVED** [review]

**Pull request merged**
