### PR TITLE
[inductor] add lowerings for hardswish/hardsigmoid/hardtanh

### PR DESCRIPTION
**Pull request by jansel**

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
💯

**Comment by jansel** [comment]
Ah whoops, I think you need to accept the invite to the repo @wconstab.  It doesn't have you marked as a valid reviewer. 

(You should be able to add yourself in the link from the top bar to meta internal.)

**Review by wconstab — APPROVED** [review]
ok, try now.

**Comment by jansel** [comment]
Whoo, thanks!

**Pull request merged**
