### PR TITLE
Fix #1466

### LINKED ISSUE #1466: TORCHDYNAMO_DYNAMIC_SHAPES=1 expects sizes returned from graph to be tuples, but AOTAutograd doesn't agree
Repro: `TORCH_SHOW_CPP_STACKTRACES=1 TORCHDYNAMO_DYNAMIC_SHAPES=1 AOT_DYNAMIC_SHAPES=1 TORCH_MONKEYPATCH_GETITEM=1 AOT_FX_GRAPHS=1 python benchmarks/torchbench.py --only hf_T5 --accuracy --backend aot_eager --training)` with symbolic-shapes branch https://github.com/pytorch/pytorch/pull/84246

We end up with this AOTAutograd graph:

```
====== Forward graph ======                                                                                                                                
class GraphModule(torch.nn.Module):                                                                                                                        
    def forward(self, primals_1, primals_2, primals_3):                                                                                                    
                                                                                                                                                           
        # Module stack: {}, File: /home/ezyang/local/pytorch-tmp-env/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:925, code: input_ids
 = input_ids.view(-1, input_shape[-1])                                                                                                                     
        sym_size = torch.ops.aten.sym_size(primals_2, 1)                                                                                                   
        view = torch.ops.aten.view.default(primals_2, [-1, sym_size])                                                                                      
                                                                             
        # Module stack: {'self_embed_tokens': 'Embedding'}, File: /home/ezyang/local/pytorch-tmp-env/lib/python3.9/site-packages/transformers/models/t5/mod
eling_t5.py:934, code: inputs_embeds = self.embed_tokens(input_ids)          
        embedding = torch.ops.aten.embedding.default(primals_1, view);  primals_1 = None                                                                   
                                                                             
        # Module stack: {}, File: /home/ezyang/local/pytorch-tmp-env/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:945, code: attention
_mask = torch.ones(batch_size, mask_seq_length).to(inputs_embeds.device)                                                                                   
        sym_size_1 = torch.ops.aten.sym_size(primals_2, 0);  primals_2 = None                                                                              
        ones = torch.ops.aten.ones.default([sym_size_1, sym_size], device = device(type='cpu'), pin_memory = False)                              
        detach = torch.ops.aten.detach.default(ones);  ones = None                                                                                         
        detach_1 = torch.ops.aten.detach.default(detach);  detach = None                                                                                   
        _to_copy = torch.ops.aten._to_copy.default(detach_1, dtype = torch.float32, layout = torch.strided, device = device(type='cuda', index=0));  detach
_1 = None                                                                    
                                                                                                                                                           
        # Module stack: {}, File: /home/ezyang/local/pytorch-tmp-env/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:948, code: encoder_a
ttention_mask = torch.ones(                                                                                                                                
        sym_size_2 = torch.ops.aten.sym_size(primals_3, 1);  primals_3 = None                                                                              
        ones_1 = torch.ops.aten.ones.default([sym_size_1, sym_size_2], dtype = torch.int64, device = device(type='cuda', index=0), pin_memory = False);  sy
m_size_2 = None                                                              
        detach_2 = torch.ops.aten.detach.default(ones_1);  ones_1 = None                                                                                   
        detach_3 = torch.ops.aten.detach.default(detach_2);  detach_2 = None                                                                               
        return [_to_copy, sym_size_1, sym_size, detach_3, embedding, view] 

aot output: (tensor([[1., 1., 1.,  ..., 1., 1., 1.],                                                                                                       
        [1., 1., 1.,  ..., 1., 1., 1.]], device='cuda:0',                                                                                                  
       grad_fn=<CompiledFunctionBackward>), 2, 1024, tensor([[1, 1, 1,  ..., 1, 1, 1],                                                                     
        [1, 1, 1,  ..., 1, 1, 1]], device='cuda:0'))  
```

but Dynamo is expecting (2, 1024)

Comments from @jansel :

Actually, perhaps we should just change `DynamicShapeVariable(len=2)` to `TupleVariable([DynamicShapeVariable, DynamicShapeVariable])`
There is actually a SizeVariable() in [lists.py](https://lists.py/). This is only a dynamic_shapes=True thing.
(dynamic_shapes=True is less tested)

We live debugged this on the stream at https://www.twitch.tv/edwardzyang

### PR DESCRIPTION
**Pull request by ezyang**
The general strategy is to represent each Size of a torch.Size individually, rather than also having a variable that collects everything. However, we have to workaround problems with torch.Size not accepting Node/Proxy as members. There's also an optimization to directly use a torch.Size proxy if we have one (which sometimes we do.)

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Can we also simplify `DynamicShapeVariable`?  I think this makes `dyn_shape_len` unused and `dyn_shape_cls` always `int`.

**Comment by ezyang** [comment]
The cls is still relevant, we still have the tests for float/bool here. Though tbh, I'm not sure why we also allow float/bool here.

**Review by jansel — APPROVED** [review]

**Comment by jansel** [comment]
> The cls is still relevant, we still have the tests for float/bool here. Though tbh, I'm not sure why we also allow float/bool here.

Perhaps `shape > 10` and `shape / 2.5`

**Comment by ezyang** [comment]
So, this is kind of annoying. Dynamo currently represents lists of proxies as `python_cls([proxy1, proxy2, ...])`. However, torch.Size does not allow Proxy to be recorded in it. But I cannot use a Tuple to record this list because then isinstance check does not report correctly.

**Comment by jansel** [comment]
What is the error?  I'd expect this to work.  You may need to fill in `proxy.node.meta["example_value"]`

**Comment by ezyang** [comment]
```
  File "/data/users/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 251, in call_function                                          
    self.push(fn.call_function(self, args, kwargs))                                                                                          
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/misc.py", line 573, in call_function                                            
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)                                                               
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/tensor.py", line 500, in call_method                                            
    *proxy_args_kwargs([self] + args, kwargs),
  File "/data/users/ezyang/torchdynamo/torchdynamo/utils.py", line 378, in proxy_args_kwargs
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/data/users/ezyang/torchdynamo/torchdynamo/utils.py", line 378, in <genexpr>
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/lists.py", line 41, in as_proxy
    return self.python_type()(self._as_proxy())
TypeError: torch.Size() takes an iterable of 'int' (item 0 is 'Proxy') 
```

Here, self.python_type is torch.Size. torch.Size does not allow non-int/symint values in itself.

**Comment by ezyang** [comment]
A "simple" fix would be to make Size be able to store proxies, but this has to be done PyTorch side, and I'm not sure how to actually test if something is a Proxy or not.

**Comment by jansel** [comment]
Ah yeah, would need a change in PyTorch.  Perhaps we can just use `tuple()` in `as_proxy()`.

**Comment by ezyang** [comment]
Can't, because tuple doesn't report the correct subclass. Is there a way to override this dynamo side?

**Comment by ezyang** [comment]
specifically, with this version of the patch

```
diff --git a/torchdynamo/variables/tensor.py b/torchdynamo/variables/tensor.py
index 0ec864de..54191720 100644
--- a/torchdynamo/variables/tensor.py
+++ b/torchdynamo/variables/tensor.py
@@ -177,14 +177,17 @@ class TensorVariable(VariableTracker):
 
             options.update(specialized_props)
             return cls(proxy, **options)
-        elif (
-            istype(example_value, (torch.Size, int, bool, float))
-            and config.dynamic_shapes
-        ):
+        elif istype(example_value, (int, bool, float)) and config.dynamic_shapes:
             proxy.node.meta["example_value"] = example_value
-            if isinstance(example_value, torch.Size):
-                options["dyn_shape_len"] = len(example_value)
             return DynamicShapeVariable(proxy, type(example_value), **options)
+        elif istype(example_value, torch.Size) and config.dynamic_shapes:
+            proxy.node.meta["example_value"] = example_value
+            sizes = []
+            for i, v in enumerate(example_value):
+                proxy_i = proxy[i]
+                proxy_i.node.meta["example_value"] = v
+                sizes.append(DynamicShapeVariable(proxy_i, int))
+            return variables.TupleVariable(sizes, **options)
         elif istype(example_value, int) and proxy.node.target in (
             torch.seed,
             operator.mod,
```

test_Size_dynamic_shapes fails with

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
                                                                      
___stack0 = 'assert %(py6)s\n{%(py6)s = %(py0)s(%(py1)s, %(py4)s\n{%(py4)s = %(py2)s.Size\n})\n}', ___stack1 = 'isinstance', ___stack2 = 'x'
___stack3 = {'@py_assert3': <class 'torch.Size'>, '@py_assert5': False, '___stack0': 'assert %(py6)s\n{%(py6)s = %(py0)s(%(py1)s, %(py4)s\n{%
(py4)s = %(py2)s.Size\n})\n}', '___stack1': 'isinstance', ...}
x = (1, 2, 3), @py_assert3 = <class 'torch.Size'>, @py_assert5 = False                                                                       

>   assert isinstance(x, torch.Size)                                                                                                         
E   AssertionError: assert False
E    +  where False = isinstance((1, 2, 3), <class 'torch.Size'>)
E    +    where <class 'torch.Size'> = torch.Size

test/test_repros.py:1105: AssertionError
```

**Comment by ezyang** [comment]
Not only does Size need to be able to store proxies, but FX seems to also require it to store Nodes. Basically, it has to be a normal pytree-able object. This doesn't seem right.

**Comment by ezyang** [comment]
I have a horrifying hack that seems to work. Pushing soon

**Comment by ezyang** [comment]
It generates some horrifying FX graphs, so we'll have to decide if we're OK with this or not. Example:

```
        # Module stack: {}, File: /data/users/ezyang/torchdynamo/test/test_repros.py:675, code: torch.arange(sorted_bucket_idx.shape[-1], device=buckets.device)                                                         
        size_5 = argsort.size()                                                                                                              
        getitem_14 = size_5[2];  size_5 = None                                                                                               
        arange_1 = torch.arange(getitem_14, device = device(type='cpu'));  getitem_14 = None                                                 
        view_1 = arange_1.view(1, 1, -1);  arange_1 = None                                                                                   
                                                                                                                                                                                                                         
        # Module stack: {}, File: /data/users/ezyang/torchdynamo/test/test_repros.py:677, code: .expand(sorted_bucket_idx.shape)             
        size_6 = argsort.size()                                                                                                              
        getitem_15 = size_6[0]                                                                                                                                                                                           
        getitem_16 = size_6[1]                                             
        getitem_17 = size_6[2];  size_6 = None                                   
                                                                                                                                                                                                                         
        # Module stack: {}, File: /data/users/ezyang/torchdynamo/test/test_repros.py:675, code: torch.arange(sorted_bucket_idx.shape[-1], device=buckets.device)                                                         
        size_7 = torch.Size([getitem_15, getitem_16, getitem_17]);  getitem_15 = getitem_16 = getitem_17 = None                                                                                                          
        expand_1 = view_1.expand(size_7);  view_1 = size_7 = None 
```

**Comment by jansel** [comment]
Hrm, we could make SizeVariable keep a pointer to the original proxy return value of `.size()` and have `.as_proxy()` just return that if it exists.

**Comment by ezyang** [comment]
ok I'll add that

**Comment by ezyang** [comment]
However, without lazy proxy creation, you're still going to end up with

```
        # Module stack: {}, File: /data/users/ezyang/torchdynamo/test/test_repros.py:677, code: .expand(sorted_bucket_idx.shape)             
        size_6 = argsort.size()                                                                                                              
        getitem_15 = size_6[0]                                                                                                                                                                                           
        getitem_16 = size_6[1]                                             
        getitem_17 = size_6[2];  size_6 = None   
```

**Comment by jansel** [comment]
I think that is fine.  Backends can DCE that away.

**Comment by jansel** [comment]
We may still need your version for when people call `torch.Size()` directly, so not sure it handles everything.

**Comment by ezyang** [comment]
intruigingly, the dce seems to already happen. After tracking the proxy:

```
call_method    size_5               size                                                        (argsort,)                                     {}
call_method    expand_1             expand                                                      (view_1, size_5)                               {}
```

**Pull request merged**
