### PR TITLE
add a skipping feature to operatorbench.py

### PR DESCRIPTION
**Pull request by Krovatkin**
This PR adds a skip file feature to easily skip segfaulting or other not easily recoverable tests if any. It works in the conjuction with the verbose option.

The verbose option additionally prints the exact test inputs e.g.

```
Running with the following inputs: ((T([256, 8, 31, 33], f16), -1, False), {})
```

this inputs can be copied as is into a skip file.
The skip file format is 
```
op,dtype,serialized_arguments
```

```
aten._softmax.default;float16;((T([16, 12, 128, 128], f16), -1, False), {})
```

### CODE REVIEW

**Comment by Krovatkin** [comment]
We could do that as well. I wasn't sure we would always get the same ordering over multiple runs.

**Comment by eellison** [comment]
It is deterministic

**Comment by desertfire** [comment]
Is the goal here to enable run `all` by skipping segfault failures? We could simply add a skip list like in test_torchinductor_opinfo.py, and eventually make the list empty.

**Comment by jansel** [comment]
We have migrated `torchdynamo` to `torch._dynamo` and will use the `pytorch/pytorch` repo for future development.  Please resubmit this PR to https://github.com/pytorch/pytorch/

More details and instructions to port this PR over can be found in https://github.com/pytorch/torchdynamo/issues/1588

**Pull request closed without merging**
