### PR TITLE
Switch torchinductor test to run on gpu pool (Part 2)

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Fixes https://github.com/pytorch/torchdynamo/issues/255

Part 2 of https://github.com/pytorch/torchdynamo/pull/258

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by jansel** [comment]
You will conflict with #257, but I think it will actually help you.

The version of functorch installed here doesn't build with the latest PyTorch.  That PR bumps to a newer version.

@SherlockNoMad

**Comment by desertfire** [comment]
@SherlockNoMad , how are we doing with this PR? Are we ready to enable GPU tests?

**Comment by voznesenskym** [comment]
At one point, I had that working in
https://github.com/pytorch/torchdynamo/pull/374 but have hit other errors.
Once we get a single job using cuda working, the rest can follow the same
pattern.

**Comment by jansel** [comment]
#549 does something similar to this using CircleCI.

**Pull request closed without merging**
