### PR TITLE
Makefile - Add option for fast pytorch build

### PR DESCRIPTION
**Pull request by anijain2305**
Adding an option for fast pytorch build. Reduces the biuld time to half.

### CODE REVIEW

**Comment by Chillee** [comment]
@anijain2305 You wanna add this into pytorch core?

**Comment by anijain2305** [comment]
@Chillee Yeah, I can do that. Any particular place where you would want this? 

I would also want to have this in Dynamo repo. All the other deps are also in this Makefile. So, its convenient for me.

**Comment by Chillee** [comment]
@anijain2305 Ed was proposing that we just add this as a flag to the PyTorch build options. So `BUILD_FAST=1 python setup.py develop` would work.

**Comment by anijain2305** [comment]
Ah I see. Thats a good idea. Let me get this in PyTorch then

**Review by jansel — APPROVED** [review]

**Comment by anijain2305** [comment]
Not needed. We can do this in PyTorch with BUILD_FAST - https://github.com/pytorch/pytorch/pull/82292

**Pull request closed without merging**
