### PR TITLE
Graph break on functions in torch.utils._pytree.*

### PR DESCRIPTION
**Pull request by yanboliang**
Fix #371

### CODE REVIEW

**Comment by voznesenskym** [comment]
Would it be possible to support this instead?

**Comment by Chillee** [comment]
I agree, I'd prefer to not graph-break on these operations.

**Comment by yanboliang** [comment]
I didn't see this is a very common use case, a graph break is just to avoid confusing error. If we find this fall back breaks too many large graphs in the future(I doubt), we can add support then.

**Comment by yanboliang** [comment]
> I agree, I'd prefer to not graph-break on these operations.

Oh, is there a lot of places using these functions? I don't have too many context.

**Comment by voznesenskym** [comment]
> I didn't see this is a very common use case, a graph break is just to avoid confusing error. If we find this fall back breaks too many large graphs in the future(I doubt), we can add support then.

I'd rather we error and fix it - I have an old branch somewhere locally I can polish off to give this a pass, do you mind if I do? or would you like to?

**Comment by yanboliang** [comment]
> I'd rather we error and fix it - I have an old branch somewhere locally I can polish off to give this a pass, do you mind if I do? or would you like to?

I can do this, it's not a big issue. Thanks.

**Comment by voznesenskym** [comment]
Discussed offline - leaving here for posterity - we need to probably support (A) A TreeSpecVariable being produced from our builder (B) the list in and out of pytree can be anything, so we need to make sure that when we access it, we are correctly tracking the objects inside with their appropriate VariableTracker objects.

**Comment by yanboliang** [comment]
I'll close this one now and send a new one to implement this feature soon. Thanks for all your suggestion!

**Pull request closed without merging**
