### PR TITLE
Revert "Remove UnspecializedNumpyVariable - stop special casing numpy…

### PR DESCRIPTION
**Pull request by desertfire**
… (#1302)"

This reverts commit 220859a37913c14980c9031323ff1f91ad0947bd.

### CODE REVIEW

**Comment by desertfire** [comment]
This helps to fix the errors seen in https://app.circleci.com/pipelines/github/pytorch/torchdynamo/2716/workflows/b36c154b-d7d9-4ac7-8e43-acadb7dd2d1e/jobs/18718.

**Comment by voznesenskym** [comment]
Hmm, I don't think CI failed on the original PR. Oh well, I'll fix it and resubmit.

**Comment by voznesenskym** [comment]
> Hmm, I don't think CI failed on the original PR. Oh well, I'll fix it and resubmit.

Oh it did, but the job is non blocking? Or it doesn't flag the PR as failing? @desertfire?

**Comment by desertfire** [comment]
> > Hmm, I don't think CI failed on the original PR. Oh well, I'll fix it and resubmit.
> 
> Oh it did, but the job is non blocking? Or it doesn't flag the PR as failing? @desertfire?

Discussed offline, so the original PR's CI run succeeded but didn't have the new tests I added in another PR.

But you raised a good question here, should we make the CircleCI jobs as "required" or "blocking". I figured out how to do that for GHA CI tasks, but I haven't found how to do that for CircleCI tasks. Maybe @malfet knows how?

**Pull request merged**
