### PR TITLE
Remove Super_SloMo from the skip list

### PR DESCRIPTION
**Pull request by desertfire**

### CODE REVIEW

**Comment by desertfire** [comment]
Super_SloMo passes locally, likely need to wait for pytorch pin update for CI to pass.

**Review by ezyang — APPROVED** [review]
can we consolidate skip lists lol

**Review by jansel — APPROVED** [review]

**Comment by desertfire** [comment]
Hmm, bumping up the pytorch pin didn't help. It fails even with AOT-eager.

```
cuda train Super_SloMo                        Traceback (most recent call last):
  File "benchmarks/torchbench.py", line 360, in <module>
    main(TorchBenchmarkRunner(), original_dir)
  File "/home/circleci/project/benchmarks/common.py", line 1757, in main
    runner.run_one_model(
  File "/home/circleci/project/benchmarks/common.py", line 1061, in run_one_model
    correct_result = model_iter_fn(
  File "benchmarks/torchbench.py", line 348, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/home/circleci/project/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/circleci/project/torchbenchmark/torchbenchmark/models/Super_SloMo/model_wrapper.py", line 34, in forward
    fCoeff = model.getFlowCoeff(trainFrameIndex, I0.device)
  File "/home/circleci/project/torchbenchmark/torchbenchmark/models/Super_SloMo/slomo_model.py", line 324, in getFlowCoeff
    C11 = C00 = - (1 - (t[ind])) * (t[ind])
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by pyjhzwh** [comment]
> Hmm, bumping up the pytorch pin didn't help. It fails even with AOT-eager.
> 
> ```
> cuda train Super_SloMo                        Traceback (most recent call last):
>   File "benchmarks/torchbench.py", line 360, in <module>
>     main(TorchBenchmarkRunner(), original_dir)
>   File "/home/circleci/project/benchmarks/common.py", line 1757, in main
>     runner.run_one_model(
>   File "/home/circleci/project/benchmarks/common.py", line 1061, in run_one_model
>     correct_result = model_iter_fn(
>   File "benchmarks/torchbench.py", line 348, in forward_and_backward_pass
>     pred = mod(*cloned_inputs)
>   File "/home/circleci/project/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/circleci/project/torchbenchmark/torchbenchmark/models/Super_SloMo/model_wrapper.py", line 34, in forward
>     fCoeff = model.getFlowCoeff(trainFrameIndex, I0.device)
>   File "/home/circleci/project/torchbenchmark/torchbenchmark/models/Super_SloMo/slomo_model.py", line 324, in getFlowCoeff
>     C11 = C00 = - (1 - (t[ind])) * (t[ind])
> RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
> ```

I always see this error. Any idea how to fix it?

**Comment by desertfire** [comment]
> > Hmm, bumping up the pytorch pin didn't help. It fails even with AOT-eager.
> > ```
> > cuda train Super_SloMo                        Traceback (most recent call last):
> >   File "benchmarks/torchbench.py", line 360, in <module>
> >     main(TorchBenchmarkRunner(), original_dir)
> >   File "/home/circleci/project/benchmarks/common.py", line 1757, in main
> >     runner.run_one_model(
> >   File "/home/circleci/project/benchmarks/common.py", line 1061, in run_one_model
> >     correct_result = model_iter_fn(
> >   File "benchmarks/torchbench.py", line 348, in forward_and_backward_pass
> >     pred = mod(*cloned_inputs)
> >   File "/home/circleci/project/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
> >     return forward_call(*input, **kwargs)
> >   File "/home/circleci/project/torchbenchmark/torchbenchmark/models/Super_SloMo/model_wrapper.py", line 34, in forward
> >     fCoeff = model.getFlowCoeff(trainFrameIndex, I0.device)
> >   File "/home/circleci/project/torchbenchmark/torchbenchmark/models/Super_SloMo/slomo_model.py", line 324, in getFlowCoeff
> >     C11 = C00 = - (1 - (t[ind])) * (t[ind])
> > RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
> > ```
> 
> I always see this error. Any idea how to fix it?



> > Hmm, bumping up the pytorch pin didn't help. It fails even with AOT-eager.
> > ```
> > cuda train Super_SloMo                        Traceback (most recent call last):
> >   File "benchmarks/torchbench.py", line 360, in <module>
> >     main(TorchBenchmarkRunner(), original_dir)
> >   File "/home/circleci/project/benchmarks/common.py", line 1757, in main
> >     runner.run_one_model(
> >   File "/home/circleci/project/benchmarks/common.py", line 1061, in run_one_model
> >     correct_result = model_iter_fn(
> >   File "benchmarks/torchbench.py", line 348, in forward_and_backward_pass
> >     pred = mod(*cloned_inputs)
> >   File "/home/circleci/project/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
> >     return forward_call(*input, **kwargs)
> >   File "/home/circleci/project/torchbenchmark/torchbenchmark/models/Super_SloMo/model_wrapper.py", line 34, in forward
> >     fCoeff = model.getFlowCoeff(trainFrameIndex, I0.device)
> >   File "/home/circleci/project/torchbenchmark/torchbenchmark/models/Super_SloMo/slomo_model.py", line 324, in getFlowCoeff
> >     C11 = C00 = - (1 - (t[ind])) * (t[ind])
> > RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
> > ```
> 
> I always see this error. Any idea how to fix it?

I don't know. I can't reproduce it locally, but since it also fails in aot_eager, I guess it relates to aot-autograd? cc @Chillee

**Comment by Chillee** [comment]
I think this is an issue with the benchmark suite, not our lowering stacks. At some point we stopped allowing tensors on CPU to be indexed by tensors on CUDA.

**Comment by desertfire** [comment]
> I think this is an issue with the benchmark suite, not our lowering stacks. At some point we stopped allowing tensors on CPU to be indexed by tensors on CUDA.

@jansel , can we have an updated version of your `torchbenchmark.tar.bz2`, https://github.com/pytorch/torchdynamo/blob/1e4361802d359615c9d4df658fac1670754a9a5c/.circleci/config.yml#L29? I  will get rid of this hack when migrating to GHA.

**Comment by jansel** [comment]
Yes I hope we can figure out how to remove that hack, it is horrible!

The `torchbenchmark.tar.bz2` line should be the same as the line right above it:
https://github.com/pytorch/torchdynamo/blob/1e4361802d359615c9d4df658fac1670754a9a5c/.circleci/config.yml#L27

I just ran that command and tar'ed up the result.

The problem was git-lfs seems completely broken in on circleci, so `git clone` doesn't pick up the data files found in torchbench.  There are access denied errors I tried and failed to fix.

**Comment by desertfire** [comment]
> Yes I hope we can figure out how to remove that hack, it is horrible!
> 
> The `torchbenchmark.tar.bz2` line should be the same as the line right above it:
> 
> https://github.com/pytorch/torchdynamo/blob/1e4361802d359615c9d4df658fac1670754a9a5c/.circleci/config.yml#L27
> 
> I just ran that command and tar'ed up the result.
> 
> The problem was git-lfs seems completely broken in on circleci, so `git clone` doesn't pick up the data files found in torchbench. There are access denied errors I tried and failed to fix.

Hmm, I am now seeing this download fails in another PR, and the same error if I run it locally. Not sure if it has anything to do with your update of the tar file.
```
wget -O torchbenchmark.tar.bz2 "https://drive.google.com/u/0/uc?id=1KvYsqipsvvv3pnNkJzME0iTemDZe0buC&export=download&confirm=t"

--2022-08-26 21:17:59--  https://drive.google.com/u/0/uc?id=1KvYsqipsvvv3pnNkJzME0iTemDZe0buC&export=download&confirm=t
Resolving drive.google.com (drive.google.com)... 172.217.15.110, 2607:f8b0:4004:82f::200e
Connecting to drive.google.com (drive.google.com)|172.217.15.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://drive.google.com/uc?id=1KvYsqipsvvv3pnNkJzME0iTemDZe0buC&export=download&confirm=t [following]
--2022-08-26 21:17:59--  https://drive.google.com/uc?id=1KvYsqipsvvv3pnNkJzME0iTemDZe0buC&export=download&confirm=t
Reusing existing connection to drive.google.com:443.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-08-8g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/lvp35ktra70og5ie5m628d0n0cd9srku/1661548650000/14493628912252031847/*/1KvYsqipsvvv3pnNkJzME0iTemDZe0buC?e=download&uuid=7d21ae8a-213a-4c85-b30c-63f6536636b1 [following]
Warning: wildcards not supported in HTTP.
--2022-08-26 21:17:59--  https://doc-08-8g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/lvp35ktra70og5ie5m628d0n0cd9srku/1661548650000/14493628912252031847/*/1KvYsqipsvvv3pnNkJzME0iTemDZe0buC?e=download&uuid=7d21ae8a-213a-4c85-b30c-63f6536636b1
Resolving doc-08-8g-docs.googleusercontent.com (doc-08-8g-docs.googleusercontent.com)... 142.251.163.132, 2607:f8b0:4004:c0b::84
Connecting to doc-08-8g-docs.googleusercontent.com (doc-08-8g-docs.googleusercontent.com)|142.251.163.132|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2022-08-26 21:17:59 ERROR 429: Too Many Requests.
```

**Comment by jansel** [comment]
We might just need to switch away from google drive.

**Comment by desertfire** [comment]
> We might just need to switch away from google drive.

Any short-term solution to unblock others? I am trying to figure out how to make git work on CircleCI, but that may take a while.

**Comment by jansel** [comment]
> > We might just need to switch away from google drive.
> 
> Any short-term solution to unblock others? I am trying to figure out how to make git work on CircleCI, but that may take a while.

Upload the file somewhere else and change the URL.

**Pull request closed without merging**
