### PR TITLE
Assertion to check if fake tensors have leaked into python

### PR DESCRIPTION
**Pull request by anijain2305**
I am seeing a fake tensor in `frame.f_locals` which is confusing to me. And I think this is wrong. Fake tensor is internal, and when someone runs a graph with real inputs, none of the output should be a FakeTensor.

So, adding an assertion to catch it somewhat early to help debug and share some repros.

### CODE REVIEW

**Comment by jansel** [comment]
Seems fine, but tests are failing

**Review by eellison — APPROVED** [review]
LGTM, but you have a couple of errors

**Comment by anijain2305** [comment]
Yes, the goal was to run CI to uncover any such issues. Happy that CI uncovered atleast one. It seems to be Fake tensor issue as well. We should fix that one.

**Review by eellison — COMMENTED** [review]
I'm actually not that familiar with `GraphArg` or how it is used. Also, the test is failing correctly returns non-fake tensors which makes me a little suspect of this. We could also error in aot_eager instead.

**Review by jansel — APPROVED** [review]
Fix tests before landing

**Comment by anijain2305** [comment]
@jansel Can you please review again as I added some `__eq_` code?

**Review by jansel — APPROVED** [review]

**Pull request merged**
