### PR TITLE
Move unspec variable to GPU if it ops with tensor on GPU

### LINKED ISSUE #1176: TorchBench training error: CUDA: Error- invalid value : speech_transformer
Repro:
```
benchmarks/torchbench.py -d cuda --inductor --training --float32 --use-eval-mode --quiet --no-skip -k  speech_transformer
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/common.py", line 1234, in run_one_model
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/torchbench.py", line 335, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/torchbench.py", line 336, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "benchmarks/torchbench.py", line 339, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/fsx/users/binbao/pytorch-release/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/speech_transformer/speech_transformer/transformer/transformer.py", line 21, in forward
    def forward(self, padded_input, input_lengths, padded_target):
  File "/fsx/users/binbao/pytorch-release/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/speech_transformer/speech_transformer/transformer/encoder.py", line 36, in forward
    def forward(self, padded_input, input_lengths, return_attns=False):
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/speech_transformer/speech_transformer/transformer/encoder.py", line 48, in <graph break in forward>
    non_pad_mask = get_non_pad_mask(padded_input, input_lengths=input_lengths)
  File "/fsx/users/binbao/torchbenchmark/torchbenchmark/models/speech_transformer/speech_transformer/transformer/encoder.py", line 50, in <graph break in forward>
    slf_attn_mask = get_attn_pad_mask(padded_input, input_lengths, length)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 889, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 880, in new_func
    return compiled_fn(args)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 228, in g
    return f(*args)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 353, in forward
    fw_outs = call_func_with_args(
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 250, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 228, in g
    return f(*args)
  File "/tmp/torchinductor_binbao/rd/crdsohhhujfn4p3xi2te6vrpge74gtietpjpk2y7lzy3xx62sqo7.py", line 380, in call
    kernel2[grid(16320)](primals_102, buf10, primals_105, buf13, 16320, 204)
  File "/fsx/users/binbao/triton/python/triton/code_gen.py", line 999, in __call__
    return self.kernel(*wargs, **kwargs, grid=self.grid)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/triton_ops/autotune.py", line 50, in __call__
    timings = {
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/triton_ops/autotune.py", line 51, in <dictcomp>
    config: self._bench(*args, config=config, **kwargs)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/triton_ops/autotune.py", line 42, in _bench
    return super()._bench(*args, config=config, **kwargs)
  File "/fsx/users/binbao/triton/python/triton/code_gen.py", line 1054, in _bench
    return triton.testing.do_bench(kernel_call)
  File "/fsx/users/binbao/triton/python/triton/testing.py", line 137, in do_bench
    fn()
  File "/fsx/users/binbao/triton/python/triton/code_gen.py", line 1053, in kernel_call
    self.kernel(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "/fsx/users/binbao/triton/python/triton/code_gen.py", line 988, in __call__
    return _triton.runtime.launch(wargs, self.fn.do_not_specialize, cache_key, self.fn.arg_names,
RuntimeError: CUDA: Error- invalid value
```

### PR DESCRIPTION
**Pull request by yanboliang**
We wrap unspecialized variable as 1-element tensor on CPU by default. If it ops with tensor whose device is GPU, we have to move it from CPU to GPU explicitly.

I verified this can fix #1176.

### CODE REVIEW

**Comment by Chillee** [comment]
Is this the right place to fix this? In PyTorch eager, doing operations between a CPU scalar tensor and a GPU tensor is totally valid.

So I'm not convinced that this should be fixed at the torchdynamo level.

**Comment by voznesenskym** [comment]
> Is this the right place to fix this? In PyTorch eager, doing operations between a CPU scalar tensor and a GPU tensor is totally valid.
> 
> 
> 
> So I'm not convinced that this should be fixed at the torchdynamo level.

Agreed. I don't think dynamo should be calling "to".

**Comment by yanboliang** [comment]
> Is this the right place to fix this? In PyTorch eager, doing operations between a CPU scalar tensor and a GPU tensor is totally valid.

Yes, it's valid operation in eager mode. I'm not sure if this is the right place, just did a quick try, lol. As I'm still in the progress of getting familiar with Inductor part code. Can you suggest where I should take a look? cc @jansel

**Comment by jansel** [comment]
Perhaps we should have a pass in inductor to bake the copy into the cudagraphs preamble.

**Comment by yanboliang** [comment]
close this in favor of https://github.com/pytorch/torchdynamo/pull/1284

**Pull request closed without merging**
