### PR TITLE
[Inductor]Autotune layout set as True by default

### PR DESCRIPTION
**Pull request by pyjhzwh**
Apply #803 by default in inductor inference; Disable tune_layout for training for now because AOTAutograd will cause grad_output to be contiguous, results in an extra kernel to transform layout (from channel-last to contiguous), mitigating the benefit of channel-last convolution.
Set tune_layout=True will increase `python benchmarks/torchbench.py --inductor-settings -dcuda --float16 -n50 --inductor` mean speedup from 2.86x to 3.22x (12% improvement)
And also minor changes in triton_conv template file to avoid triton error.

fp16 inference torchinductor speedup (tuned_layout=False vs tuned_layout=True)
name | batch_size | baseline | tuned_layout
-- | -- | -- | --
BERT_pytorch | 16 | 2.3444 | 2.3898
Background_Matting | 1 | 1.4044 | 2.147
LearningToPaint | 96 | 1.3108 | 2.265
Super_SloMo | 0 | 0 | 0
alexnet | 128 | 1.1682 | 1.4026
attention_is_all_you_need_pytorch | 32 | 5.2247 | 5.3949
dcgan | 256 | 1.196 | 1.436
densenet121 | 64 | 1.6098 | 2.232
dlrm | 1000 | 1.2946 | 1.3603
drq | 1 | 4.6813 | 4.8482
hf_Albert | 1 | 5.0707 | 5.048
hf_Bart | 1 | 3.6774 | 2.95
hf_Bert | 1 | 3.9618 | 3.9155
hf_DistilBert | 1 | 3.6231 | 3.6839
hf_GPT2 | 1 | 2.15 | 2.1377
hf_T5 | 1 | 2.8717 | 2.8755
maml_omniglot | 1 | 3.8799 | 4.8335
mnasnet1_0 | 32 | 2.3934 | 3.3867
mobilenet_v2 | 16 | 4.0192 | 5.2684
mobilenet_v3_large | 32 | 2.6653 | 3.7962
nvidia_deeprecommender | 256 | 0.8799 | 0.8811
opacus_cifar10 | 64 | 4.6303 | 5.5587
pyhpc_equation_of_state | 1048576 | 18.7243 | 17.1679
pyhpc_turbulent_kinetic_energy | 1048576 | 0.9459 | 0.9203
pytorch_CycleGAN_and_pix2pix | 1 | 2.3944 | 2.0589
pytorch_stargan | 16 | 0.8085 | 0.7996
pytorch_struct | 200 | 3.0201 | 3.5326
pytorch_unet | 1 | 1.7728 | 1.8695
resnet18 | 8 | 3.4273 | 5.264
resnet50 | 32 | 1.5313 | 2.0336
resnext50_32x4d | 8 | 3.4981 | 4.7132
shufflenet_v2_x1_0 | 64 | 2.7377 | 4.2453
soft_actor_critic | 256 | 2.6877 | 2.7468
squeezenet1_1 | 16 | 3.2956 | 4.1206
timm_efficientdet | 0 | 0 | 0
timm_efficientnet | 64 | 1.4525 | 2.1242
timm_nfnet | 128 | 1.8745 | 2.5661
timm_regnet | 32 | 3.3165 | 3.6035
timm_resnest | 32 | 1.5514 | 1.7155
timm_vision_transformer | 8 | 2.2552 | 2.2058
timm_vovnet | 32 | 1.3527 | 1.6406
vgg16 | 4 | 1.2434 | 1.5925
  |   |   |  
  |   | e062891bd4021a5e3913b87ac77da66a9f737396 | e062891bd4021a5e3913b87ac77da66a9f737396
gmean |   | 2.29 | 2.64
mean |   | 2.86 | 3.22

fp32 inference torchinductor speedup (tuned_layout=False vs tuned_layout=True)
name | batch_size | baseline | tuned_layout
-- | -- | -- | --
BERT_pytorch | 16 | 1.6506 | 1.6765
Background_Matting | 1 | 1.3716 | 1.3454
LearningToPaint | 96 | 1.2396 | 1.2906
Super_SloMo | 0 | 0 | 0
alexnet | 128 | 1.1044 | 1.1926
attention_is_all_you_need_pytorch | 32 | 3.4137 | 3.5026
dcgan | 256 | 1.0725 | 3.0076
densenet121 | 64 | 1.476 | 1.4904
dlrm | 1000 | 1.1092 | 1.1315
drq | 1 | 3.6 | 3.569
hf_Albert | 1 | 3.6831 | 3.7222
hf_Bart | 1 | 3.6004 | 3.6792
hf_Bert | 1 | 2.8785 | 2.8963
hf_DistilBert | 1 | 2.6527 | 2.6684
hf_GPT2 | 1 | 1.5853 | 1.5875
hf_T5 | 1 | 2.3751 | 2.3753
maml_omniglot | 1 | 3.7067 | 3.8656
mnasnet1_0 | 32 | 1.2857 | 1.7176
mobilenet_v2 | 16 | 2.5354 | 3.0395
mobilenet_v3_large | 32 | 1.7887 | 2.2519
nvidia_deeprecommender | 256 | 0.8215 | 0.846
opacus_cifar10 | 64 | 3.41 | 3.5889
pyhpc_equation_of_state | 1048576 | 24.0489 | 20.0641
pyhpc_turbulent_kinetic_energy | 0 | 0 | 0
pytorch_CycleGAN_and_pix2pix | 1 | 1.911 | 1.5343
pytorch_stargan | 16 | 1.0819 | 1.0242
pytorch_struct | 200 | 3.2804 | 3.3176
pytorch_unet | 1 | 1.6311 | 1.5365
resnet18 | 8 | 2.3683 | 2.6675
resnet50 | 32 | 1.416 | 1.4511
resnext50_32x4d | 8 | 1.8714 | 2.2374
shufflenet_v2_x1_0 | 64 | 1.8742 | 2.3106
soft_actor_critic | 256 | 2.1474 | 2.1438
squeezenet1_1 | 16 | 2.2266 | 2.5084
timm_efficientdet | 0 | 0 | 0
timm_efficientnet | 64 | 1.3174 | 1.8043
timm_nfnet | 0 | 0 | 0
timm_regnet | 32 | 1.2142 | 1.1796
timm_resnest | 32 | 1.4587 | 1.5354
timm_vision_transformer | 8 | 2.0012 | 1.9668
timm_vovnet | 32 | 1.2345 | 1.2438
vgg16 | 4 | 1.1699 | 1.1391
yolov3 | 0 | 0 | 0
  |   |   |  
  |   | e062891bd4021a5e3913b87ac77da66a9f737396 | e062891bd4021a5e3913b87ac77da66a9f737396
gmean |   | 1.83 | 1.94
mean |   | 2.41 | 2.45

### CODE REVIEW

**Comment by pyjhzwh** [comment]
Blocked by #957

**Review by jansel — APPROVED** [review]

**Comment by desertfire** [comment]
> Blocked by #957

My recent CI runs are ok. You can rebase and give it another try.

Very nice perf gain. Good job!

**Comment by pyjhzwh** [comment]
> > Blocked by #957
> 
> My recent CI runs are ok. You can rebase and give it another try.
> 
> Very nice perf gain. Good job!

Thanks. But still
```
    from functorch.compile import get_aot_compilation_context
E   ImportError: cannot import name 'get_aot_compilation_context' from 'functorch.compile' 
```
Because Torchdynamo uses PYTORCH_VERSION ?= dev20220807 but the new `get_aot_compilation_context` was merged a few days ago.

**Comment by pyjhzwh** [comment]
> > > Blocked by #957
> > 
> > 
> > My recent CI runs are ok. You can rebase and give it another try.
> > Very nice perf gain. Good job!
> 
> Thanks. But still
> 
> ```
>     from functorch.compile import get_aot_compilation_context
> E   ImportError: cannot import name 'get_aot_compilation_context' from 'functorch.compile' 
> ```
> 
> Because Torchdynamo uses PYTORCH_VERSION ?= dev20220807 but the new `get_aot_compilation_context` was merged a few days ago.

Solved by #939

**Comment by jansel** [comment]
We have migrated `torchdynamo` to `torch._dynamo` and will use the `pytorch/pytorch` repo for future development.  Please resubmit this PR to https://github.com/pytorch/pytorch/

More details and instructions to port this PR over can be found in https://github.com/pytorch/torchdynamo/issues/1588

**Pull request closed without merging**
